### ISSUE TITLE
gyp build error on windows 32, node 0.8.11

### ISSUE THREAD

**Issue by adamramadhan** [phusion/node-sha3#1]
heres the trace

    gyp http 200 http://nodejs.org/dist/v0.8.11/x64/node.lib
    Traceback (most recent call last):
      File "C:\Users\dimazm\.node-gyp\0.8.11\tools\gyp\gyp", line 18, in <module>
        sys.exit(gyp.main(sys.argv[1:]))
      File "C:\Users\dimazm\.node-gyp\0.8.11\tools\gyp\pylib\gyp\__init__.py", line
    511, in main
        return gyp_main(args)
      File "C:\Users\dimazm\.node-gyp\0.8.11\tools\gyp\pylib\gyp\__init__.py", line
    494, in gyp_main
        options.circular_check)
      File "C:\Users\dimazm\.node-gyp\0.8.11\tools\gyp\pylib\gyp\__init__.py", line
    133, in Load
        depth, generator_input_info, check, circular_check)
      File "C:\Users\dimazm\.node-gyp\0.8.11\tools\gyp\pylib\gyp\input.py", line 237
    8, in Load
        depth, check)
      File "C:\Users\dimazm\.node-gyp\0.8.11\tools\gyp\pylib\gyp\input.py", line 358
    , in LoadTargetBuildFile
        includes, True, check)
      File "C:\Users\dimazm\.node-gyp\0.8.11\tools\gyp\pylib\gyp\input.py", line 208
    , in LoadOneBuildFile
        raise Exception("%s not found (cwd: %s)" % (build_file_path, os.getcwd()))
    Exception: binding.gyp not found (cwd: C:\Windows) while trying to load binding.
    gyp
    gyp ERR! configure error
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (c:\Program Files\nodejs\node_module
    s\npm\node_modules\node-gyp\lib\configure.js:350:16)
    gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:96:17)
    gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
    les\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Windows
    gyp ERR! node -v v0.8.11
    gyp ERR! node-gyp -v v0.6.11
    gyp ERR! not ok
    npm ERR! sha3@1.0.0 install: `node-gyp rebuild`
    npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
    npm ERR!
    npm ERR! Failed at the sha3@1.0.0 install script.
    npm ERR! This is most likely a problem with the sha3 package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls sha3
    npm ERR! There is likely additional logging output above.

    npm ERR! System Windows_NT 6.1.7601
    npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodej
    s\\node_modules\\npm\\bin\\npm-cli.js" "install" "sha3"
    npm ERR! cwd \\192.168.0.102\projects\_working\netcoid\netcoid\jono
    npm ERR! node -v v0.8.11
    npm ERR! npm -v 1.1.62
    npm ERR! code ELIFECYCLE
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     \\192.168.0.102\projects\_working\netcoid\netcoid\jono\npm-debug.lo
    g
    npm ERR! not ok code 0

**Comment by parkr** [comment]
Check out the latest version and let me know if it's been fixed.
