### ISSUE TITLE
Keccak != SHA-3

### ISSUE THREAD

**Issue by mpaland** [phusion/node-sha3#14]
After the last update in 4/2014 SHA-3 is not exactly Keccak anymore. NIST added padding of 01.
So SHA3(256, "") != Keccak(256, "")
Please replace the name SHA-3 with Keccak to avoid confusion or make SHA3 compatible according to the actual NIST text vectors.
Thanx.

**Comment by parkr** [comment]
Sorry, can you elaborate on the differences?

**Comment by mpaland** [comment]
Please see http://en.wikipedia.org/wiki/SHA-3 for test vectors.
The latest NIST draft explains the details, or have a look here:
https://stbuehler.de/blog/article/2014/05/15/some_notes_on_sha-3.html

**Comment by parkr** [comment]
Our test data is all based on the Keccak input and output: https://github.com/phusion/node-sha3/tree/master/test/data

**Comment by mpaland** [comment]
Yes, I know, but it should be based on SHA-3 now - that's why I created this issue.

**Comment by parkr** [comment]
Sorry, I didn't understand: 

> Please replace the name SHA-3 with Keccak to avoid confusion or make SHA3 compatible according to the actual NIST text vectors.

We can't replace the name – we have always been `sha3` on npmjs.org. It would make more sense to just document that we're the pre-NIST version when SHA3 and Keccak were virtually identical.

**Comment by mpaland** [comment]
But actually you don't deserve the name SHA-3 anymore ;-)
It's pretty fucked up what NIST did: Add some padding bits while the first draft has been around for years.
Problem is if some SHA-3 hashes were created with your lib and you modify the algo now, all hashes will fail. On the other hand you don't have compatibility to libs which implement the new standard.

My advice: Keep the name (of course), implement the new standard and a "backward compatibility" switch. The change isn't very big.

**Comment by parkr** [comment]
> My advice: Keep the name (of course), implement the new standard and a "backward compatibility" switch. The change isn't very big.

@mpaland Want to submit a PR for this?

**Comment by makevoid** [comment]
To solve interop issues, this library implements the "new" SHA3: [js-sha3](https://github.com/emn178/js-sha3) | [js-sha3 npm](https://www.npmjs.com/package/js-sha3), I imagine it's slower because it's in JS and not C++ but if you need interop. with other SHA3 libraries from other languages (like the one in golang stdlib) you'll need to switch to js-sha3.

**Comment by steakknife** [comment]
Resolved in PR #25
