### ISSUE TITLE
Sha3 digest != Crypto digest

### ISSUE THREAD

**Issue by NawarA** [phusion/node-sha3#15]
The Digest() should accept "base64" encoding in addition to the existing "binary" and "hex". 

Also, Digest should return a slow buffer by default. There are many benefits to returning the slow buffer. 

For example, a 512-bit digest produces a 96 byte hex value, while the slow buffer is a 64 byte value. It should be possible to get 64 bytes (the real size) from a 512-bit hash, not just 96 bytes.

**Comment by parkr** [comment]
This library is in maintenance mode at this point. If you have time to submit a PR, I'd be happy to review.

@FooBarWidget, any thoughts?

**Comment by FooBarWidget** [comment]
I haven't touched this library in years, nor do I have time to, so I don't have many thoughts about this issue. :) I'll leave it up to you to decide what to do.

**Comment by parkr** [comment]
Closing as wontfix for now.
