### ISSUE TITLE
Doesn't install.

### ISSUE THREAD

**Issue by LordLambda** [phusion/node-sha3#16]
I'm running on Windows 7 64 bit. 

Heres the NPM Debug log:http://pastebin.com/49SfBmiu
 
I also caught this message in the console:
addon.obj : error LNK2001: unresolved external symbol "enum mode::encoding __cdecl node::ParseEncoding(class v8::Isolate *,class v8::Handle<class v8::Value>,enum node::encoding)" (?ParseEncoding@node@@YA?AW4encoding@1@PAVIsolate@v8@@V?$Handle@VValue@v8@@@4W421@@Z)

**Comment by parkr** [comment]
Check out 1.2.0. Should work fine now.

**Comment by mathieurousseau** [comment]
I am having the same issue, using 1.2.0
  win_delay_load_hook.c
     Creating library C:\Mathieu\NAR\FSIT\Ethereum\EPR_V3\Buyer\node_modules\sha3\build\Release\sha3.lib and object C:\Mathieu\NAR\FSIT\Ethe
  reum\EPR_V3\Buyer\node_modules\sha3\build\Release\sha3.exp
addon.obj : error LNK2001: unresolved external symbol "enum node::encoding __cdecl node::ParseEncoding(class v8::Handle<class v8::Value>,enu
m node::encoding)" (?ParseEncoding@node@@YA?AW4encoding@1@V?$Handle@VValue@v8@@@v8@@W421@@Z) [C:\Mathieu\NAR\FSIT\Ethereum\EPR_V3\Buyer\node
_modules\sha3\build\sha3.vcxproj]
C:\Mathieu\NAR\FSIT\Ethereum\EPR_V3\Buyer\node_modules\sha3\build\Release\sha3.node : fatal error LNK1120: 1 unresolved externals [C:\Mathie
u\NAR\FSIT\Ethereum\EPR_V3\Buyer\node_modules\sha3\build\sha3.vcxproj]

npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
