### ISSUE TITLE
node.js 4.0.0 doesn't support this module.

### ISSUE THREAD

**Issue by breaklee** [phusion/node-sha3#20]

**Comment by breaklee** [comment]
when load this module on node.js 4.0.0,

Segmentation fault: 11

rasied.

**Comment by freeneutron** [comment]
Anahter promlem:

 npm install sha3
-
> sha3@1.2.0 install /media/sf_project/a0/a1/node_modules/sha3
> node-gyp rebuild

make: Entering directory `/media/sf_project/a0/a1/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
In file included from /root/.node-gyp/4.0.0/include/node/node.h:42,
                 from ../src/addon.cpp:1:
/root/.node-gyp/4.0.0/include/node/v8.h:336: ошибка: expected unqualified-id before ‘using’

**Comment by parkr** [comment]
Looks like it does now!
