### ISSUE TITLE
Cannot find module 'sha3'

### ISSUE THREAD

**Issue by bawejakunal** [phusion/node-sha3#22]
I installed `'sha3' package` from `npm` but when I tried executing the sample javascript shown on https://www.npmjs.com/package/sha3 I am getting the error as:

Cannot find module 'sha3' from '/home/mypc/Desktop/browser'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)

I tried on multiple machines and even on the tonic webpage(https://tonicdev.com/npm/sha3) but getting the same error everywhere.

**Comment by parkr** [comment]
Run `npm install sha3` from inside `/home/mypc/Desktop/browser` and it should work. It's looking for `browser/node_modules/sha3` and not finding it.

**Comment by bawejakunal** [comment]
The directory structure of my installation is already '/home/mypc/Desktop/browser/node_modules/sha3' which should work because I have certain other packages which are working fine. Thanks

**Comment by parkr** [comment]
Is it a part of your browserify config? Is that looking in your package.json?

**Comment by bawejakunal** [comment]
Yes it is part of browserify config.

**Comment by parkr** [comment]
Interesting. This module is based on C++ extensions -- can browserify package those up? I'd expect it to work only with pure JavaScript libraries.
