### ISSUE TITLE
browserify-sha3

### ISSUE THREAD

**Issue by wanderer** [phusion/node-sha3#23]
Hello, I maintain [browserify-sha3 ](https://github.com/wanderer/browserify-sha3). It would be really convenient to merge the projects. So you don't have to explicitly require a some to code your code browser friendly. Would there be interest in a PR?

**Comment by parkr** [comment]
It looks like you're using a full-JS lib? Might be some incompatibilities here.

**Comment by wanderer** [comment]
If there is any I will fix them.

**Comment by fanatid** [comment]
@wanderer @parkr I think this issue is not relevant anymore. I wrote bindings + purejs: https://github.com/cryptocoinjs/keccak
