### ISSUE TITLE
Build fails on OSX El Capitan

### ISSUE THREAD

**Issue by MaiaVictor** [phusion/node-sha3#24]
v$ npm install sha3
    |
    > sha3@1.2.0 install /Users/v/Crypto/btc/node_modules/sha3
    > node-gyp rebuild

    CXX(target) Release/obj.target/sha3/src/addon.o
    CXX(target) Release/obj.target/sha3/src/displayIntermediateValues.o
    CXX(target) Release/obj.target/sha3/src/KeccakF-1600-reference.o
    CXX(target) Release/obj.target/sha3/src/KeccakNISTInterface.o
    CXX(target) Release/obj.target/sha3/src/KeccakSponge.o
    SOLINK_MODULE(target) Release/sha3.node
    ld: library not found for -lgcc_s.10.5
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [Release/sha3.node] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Darwin 15.0.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/v/Crypto/btc/node_modules/sha3
    gyp ERR! node -v v4.1.0
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok
    npm ERR! Darwin 15.0.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sha3"
    npm ERR! node v4.1.0
    npm ERR! npm  v2.14.3
    npm ERR! code ELIFECYCLE

    npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the sha3 package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls sha3
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/v/Crypto/btc/npm-debug.log

**Comment by parkr** [comment]
> ld: library not found for -lgcc_s.10.5

Looks like you're missing gcc. Install it (via Homebrew is probably best) and this should be fixed.

**Comment by kKreics** [comment]
Ran into this problem today. I have gcc installed but still no positive result comes of this. What could be the problem?
Log:
`ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/sha3.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/usr/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/usr/.nvm/versions/node/v5.5.0/bin/node" "/Users/usr/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/usr/node_modules/sha3
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN ENOENT ENOENT: no such file or directory, open '/Users/usr/package.json'
npm WARN EPACKAGEJSON usr No description
npm WARN EPACKAGEJSON usr No repository field.
npm WARN EPACKAGEJSON usr No README data
npm WARN EPACKAGEJSON usr No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/usr/.nvm/versions/node/v5.5.0/bin/node" "/Users/usr/.nvm/versions/node/v5.5.0/bin/npm" "install" "sha3"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sha3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sha3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/usr/npm-debug.log
`

**Comment by tlkahn** [comment]
Same issue. any updates?

**Comment by canterberry** [comment]
Upgrading to v1.2.3 or v2.0.4 should fix any build issues. If sha3 is a transitive dependency (i.e: it's not being used directly, but by a library you're using), then you can follow the steps in [this comment](https://github.com/phusion/node-sha3/issues/32#issuecomment-490157571) (but using sha3 version 1.2.3), and/or submit an issue or pull request on that library to upgrade this package.

v2.x is a portable pure JavaScript implementation with no post-install build steps.
v1.x is a native C implementation with JavaScript bindings, which is faster, but is not portable to web browsers and requires a post-install build step with some extra global dependencies and risk of drift with OS and Node.js runtime deprecations.
