### ISSUE TITLE
✨ Add support for SHA-3

### ISSUE THREAD

**Issue by canterberry** [phusion/node-sha3#36]
Follow-up to #14.

Currently this library only supports Keccak, which although has a shared history with SHA-3, produces a different result.

The goal of this issue is to devise a plan to introduce SHA-3 into this library, in addition to the current Keccak implementation, in the least impactful manner.

The phased transition from Keccak to SHA-3 as the primary algorithm provided by this library is as follows:

 1. Introduce an API wherein either a Keccak or SHA-3 hash can be produced. (TBD)
 2. In a new *minor release*, the current API ,`new SHA3.SHA3Hash()`, should be marked as *deprecated* with a note to use the new API introduced in phase 1. For compatibility, `new SHA3.SHA3Hash()` should be aliased to initializing a new *Keccak* hash using the new API.
 3. In a new *major release*, the current API, `new SHA3.SHA3Hash()`, should be removed, and the path of least resistance in this library, in keeping with the library's name, should be to produce a SHA-3 hash rather than a Keccak hash.

In addition to the code-level changes related to each of the above phases, there should be ample notice and engagement with dependent projects, wherever possible, to help ensure a smooth transition.

**Comment by macalinao** [comment]
I just spent an unforunate amount of time debugging this. This should be called node-keccak.

**Comment by steakknife** [comment]
Seems like a `really_sha3_instead_of_keccak` option to change the padding would be the way to go without breaking existing code.

**Comment by canterberry** [comment]
@steakknife @miguelmota

This is delivered in #44, which updates the API to the following:

 * `new SHA3.SHA3Hash(256)` works exactly as it does today.
 * `new SHA3.Keccak(256)` initializes a Keccak-256 hash with the same API as above.
 * `new SHA3.SHA3(256)` initializes a SHA3-256 hash with the same API as above.

**Comment by canterberry** [comment]
Fixed in v2.0.0.
