### ISSUE TITLE
Broken NPM package

### ISSUE THREAD

**Issue by orlandoc01** [phusion/node-sha3#39]
It seems like on a recent release, you removed support for node engines that are less than version `8.11`. However, this new release was registered as a `patch` release, which is an upgrade from `1.2.0` to `1.2.1`. As a result, most package managers interpret this upgrade as a nonbreaking change and will attempt to install `1.2.1` instead of `1.2.0`, assuming that it's safer. However, this is *NOT* the case, as anyone who uses Node 6 or 7 (like our project) will suddenly have their build process broken as our package managers attempt to fetch the patch, only to see the Node version is incompatible. For now, we are hardcoding `1.2.0` as an explicit dependency even though its actually one of our transitive dependencies but I have a feeling that this will break a lot of other people's build processes as well. If it's not too inconvenient, it would be helpful to pull this version from the NPM registry and instead, release this new version as as a new minor version,`1.3.0`, because the update is actually a breaking change which breaks the typical semantics of a `patch`. Just a suggestion though 😃

**Comment by canterberry** [comment]
Thanks for the report, @orlandoc01! Honestly, I hadn't realized that there were still projects out there using versions prior to 8.x, so the patch version seemed appropriate.

This is, of course, a serious backwards-compatibility issue and will be addressed promptly. Future updates will be sure to honor all non-EOL Node.js versions listed by the Node.js working group in [nodejs/Release](https://github.com/nodejs/Release#release-schedule).

**Comment by canterberry** [comment]
Thanks again for the report, @orlandoc01. v1.2.2 has now been released, which should resolve the issue. If you are still having any trouble, do let me know. I'm sorry for the trouble!

**Comment by orlandoc01** [comment]
Thanks! Yeah, we want to update soon but we appreciate the backwards support 😄
