### ISSUE TITLE
🏇 Unroll loops in Keccak permutations

### ISSUE THREAD

**Issue by canterberry** [phusion/node-sha3#51]
In the research for #44, I found that unrolling the loops within each Keccak permutation had a significant positive impact on performance. Try this again, and provide benchmarks to demonstrate the impact on performance.

[Loop unrolling](https://en.wikipedia.org/wiki/Loop_unrolling) is a technique that violates [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), but can result in significant performance gains where loops occur very frequently. Keccak permutations are one such use case where the trade-off can be justified, as the performance gains can be hundred-fold.

**Comment by davidmurdoch** [comment]
You could try throwing something like https://prepack.io/ at it which can do loop unrolling at build time.

**Comment by canterberry** [comment]
#52 is a first pass attempt at improving performance by converting the `permute()` implementation into a code generator (vs a direct implementation). This seemed much easier than manually unrolling all the loops and caching all the array lookups. Unfortunately, the performance improvement I would have hoped to see was not evident. I'm not planning to continue with that particular strategy.

Before starting down that path, I took a look at Prepack. In my first few attempts, I wasn't able to get it to work. Maybe it only works with apps (vs libraries)? I also noticed it is marked as "not ready for production use yet" so it may just be premature. I do like the idea of bringing C-style optimizations to the JavaScript build toolchain.

**Comment by davidmurdoch** [comment]
It is possible the function is large enough that some internal V8 optimizations are skipped. Try running `node --trace-deopt --trace-opt ./path/to/benchmark.js` to see if the optimizer is bailing on this large function (you _might_ need to name the function so you can find it in the output).

**Comment by canterberry** [comment]
Performance optimizations have been added in #53. As it turns out, there were many gains to be had from techniques other than loop unrolling.

**Comment by canterberry** [comment]
Closing via #53.
