### ISSUE TITLE
Add missing types to index.d.ts

### ISSUE THREAD

**Issue by bokunobaka** [phusion/node-sha3#88]
Sorry for not including these in the previous issue but _tsc_  currently complains that Buffer and BufferEncoding are unknown. Buffer comes from the 'buffer' npm package, but I couldn't find BufferEncoding anywhere in the project but made the class based on the information in the README.md

This can be added to the beginning of index.d.ts to make it happy
```
import { Buffer } from 'buffer';

declare class BufferEncoding {
    buffer: Buffer;
    format: string;
    padding?: number;
}
```

**Comment by canterberry** [comment]
Fixed in #92. Will be shipped in v2.1.4.
