### ISSUE TITLE
TypeScript definition for SHAKE constructor is wrong.

### ISSUE THREAD

**Issue by cakoose** [phusion/node-sha3#90]
Currently, the `SHA3` and `SHAKE` symbols have the same TypeScript definition.  The constructor signature looks like this:

```
    constructor(size?: 224 | 256 | 384 | 512);
```

That signature is fine for `SHA3` but is incorrect for `SHAKE`.  I get a type error when trying to construct `new SHAKE(128)`.

**Comment by cakoose** [comment]
One option:
1. Remove the `constructor` from the common interface.  Have each one define their own.
2. Export the `Hasher` type, so I have a type for the common interface.

**Comment by canterberry** [comment]
Good eye! Option 1 sounds good to me. Alternatively, a third option would be to remove the enumeration of possible numeric values from the TypeScript definition and instead declare `size` as a basic number. There is [already input validation](https://github.com/phusion/node-sha3/blob/master/src/index.js#L9) to ensure the algorithm used receives one of its allowed hash sizes, so enforcement of this at the TypeScript layer may be overkill.

**Comment by septs** [comment]
![image](https://user-images.githubusercontent.com/3842474/105798768-dddb4000-5fcd-11eb-9b17-f8aa60e50ac0.png)

wait for merge
