### ISSUE TITLE
Zero dependency

### ISSUE THREAD

**Issue by septs** [phusion/node-sha3#93]
Remove `buffer` dependency

**Comment by canterberry** [comment]
The Buffer dependency is necessary for compatibility with web browsers, which do not provide a Buffer global. It is unnecessary for Node.js, though, in which case the buffer package is expected to be a shim, or at least compatible with the Node.js implementation.

Is there a practical benefit to removing the Buffer dependency? The implementation of the sha3 package draws significant benefit from Buffer, and removing it as a dependency would require a significant rewrite. It would take a tremendous value prop to trigger dropping it altogether.

**Comment by septs** [comment]
https://github.com/phusion/node-sha3/blob/7b88fc1c559c06b7b236c81d87cccbe4c6e7acd4/src/index.js
https://github.com/phusion/node-sha3/blob/7b88fc1c559c06b7b236c81d87cccbe4c6e7acd4/src/sponge/index.js

only two file use `buffer` dependency.

but this is break change.
